---
title: "Comparisons between fungi, information content of ATG context"
author: Edward Wallace, ewjwallace@gmail.com
date: 12 Oct 2018
output:
  # html_notebook: default
  html_document:
    toc: true
    toc_depth: 4
---

# Summary

This summarizes relationships of ATG context between fungi. It relies on data output generated from the files *SPECIESNAME*ATGContext.Rmd
    
### Load Packages

```{r setup,message=FALSE,echo=FALSE,cache=FALSE}
knitr::opts_chunk$set(warning=FALSE,message=FALSE,echo=FALSE,cache=TRUE,
                      results="hide",
                      fig.path="figure/CompareATGContext-",
                      cache.path="cache/CompareATGContext-")
# load common functions
source("../SharedScripts/sharedScripts.R")
# setwd("~/Repos/CryptoTranscriptome2018/ATGContextOthers/")
```

### Load data

```{r load_infon}

# infon_Ca_zero <- tibble(Genes="CytoRibo",ATG="aATG",Infon=NA,Organism="Ca")

infon_tbl <- bind_rows(
    read_tsv("data_out/inf_content_narrow_Sc.txt") %>% 
        mutate(Organism="Sc"),
    read_tsv("data_out/inf_content_narrow_Ca.txt") %>% 
        mutate(Organism="Ca"),
    read_tsv("data_out/inf_content_narrow_Nc.txt") %>% 
        mutate(Organism="Nc"),
    read_tsv("data_out/inf_content_narrow_Sp.txt") %>% 
        mutate(Organism="Sp"),
    read_tsv("../ATGContext/data_out/inf_content_narrow_H99.txt") %>% 
        mutate(Organism="Cn"),
    read_tsv("../ATGContext/data_out/inf_content_narrow_JEC21.txt") %>% 
        mutate(Organism="Cd")
) %>%
    mutate(Genes=factor(Genes, levels=c("All","HiTrans","CytoRibo")),
           Organism=factor(Organism,levels=c("Cn","Cd","Nc","Sp","Ca","Sc"))
    )

infon_tbl
```

### Inf content narrow by organism and gene list

```{r inf_content,fig.height=3,fig.width=4}
ggplot(data = infon_tbl %>% filter(ATG=="aATG"),
       aes(x=Organism,y=Infon,fill=Genes)) +
    geom_col(position="dodge") +
    scale_fill_manual(values=c("All"="dodgerblue",
                               "HiTrans"="darkblue",
                               "CytoRibo"="purple")) +
    scale_y_continuous("Information content\n-5:aATG (bits)",
                       expand=c(0,0)) 
    
```

### Inf content narrow by gene list and organism

```{r inf_content_bygenes,fig.height=3,fig.width=4}
ggplot(data = infon_tbl %>% filter(ATG=="aATG"),
       aes(x=Genes,y=Infon,fill=Organism)) +
    geom_col(position="dodge") +
    scale_fill_brewer(type = "qual",palette=2) +
    scale_y_continuous("Information content\n-5:aATG (bits)",
                       expand=c(0,0)) +
    theme(panel.grid.major.y=element_line(colour="grey90"))
    
```

### Inf content per base


```{r load_info_perbase}

# infon_Ca_zero <- tibble(Genes="CytoRibo",ATG="aATG",Infon=NA,Organism="Ca")

infon_perbase <- bind_rows(
    read_tsv("data_out/inf_content_perbase_Sc.txt") %>% 
        mutate(Organism="Sc"),
    read_tsv("data_out/inf_content_perbase_Ca.txt") %>% 
        mutate(Organism="Ca"),
    read_tsv("data_out/inf_content_perbase_Nc.txt") %>% 
        mutate(Organism="Nc"),
    read_tsv("data_out/inf_content_perbase_Sp.txt") %>% 
        mutate(Organism="Sp"),
    read_tsv("../ATGContext/data_out/inf_content_perbase_H99.txt") %>% 
        mutate(Organism="Cn"),
    read_tsv("../ATGContext/data_out/inf_content_perbase_JEC21.txt") %>% 
        mutate(Organism="Cd")
) %>%
    mutate(Organism=factor(Organism,levels=rev(c("Cn","Cd","Nc","Sp","Ca","Sc")))
    )

infon_perbase
```


```{r plot_inf_perbase,fig.height=4,fig.width=4}
posbreaks <- c(1,10,13:15,24)
poslabels <- c("-12","-3","A","T","G","+12")
inf_limits <- c(0,2)

ggplot(data=infon_perbase %>%
           gather(key = "Genes",value="Infon",-i,-Pos,-Organism) %>%
           mutate(Genes=factor(Genes, levels=c("All","HiTrans","CytoRibo")) ),
       aes(x=i,y=Organism,fill=Infon) ) +
    geom_tile() + 
    scale_fill_gradient(low="white",high="darkblue",limits=inf_limits) + 
    scale_x_continuous(breaks=posbreaks,labels=poslabels,expand=c(0,0)) + 
    scale_y_discrete(expand=c(0,0)) + 
    facet_wrap(~Genes,ncol=1,scales="free") + 
    theme(axis.title=element_blank())
```
