---
title: "Near-AUG starts for C. neoformans"
author: Edward Wallace, ewjwallace@gmail.com
date: 12 Oct 2018
output:
  # html_notebook: default
  html_document:
    toc: true
    toc_depth: 4
---

# Summary


Near-AUG near-cognate start codons


### Load Packages

```{r setup,message=FALSE,echo=FALSE,cache=FALSE}
knitr::opts_chunk$set(warning=FALSE,message=FALSE,echo=TRUE,cache=FALSE,
                      results="show",
                      fig.path="figure/nearAUGstarts-",
                      cache.path="cache/nearAUGstarts-")
# load common functions
source("../SharedScripts/sharedScripts.R")
# setwd("~/Repos/CryptoTranscriptome2018/ATGContext/")
```

## Process H99

```{r process_H99,results="show"}
expand_threeprime_nrstarts(txinfile = "../CDSFasta/data_in/H99_10p_up12dwn9_CDS_with_120bputrs.fa",
                        CDSoutfile="../CDSFasta/data_out/H99_10p_up12dwn9_CDS_with_nrAUG_5pext.fa",
                        protoutfile="../ProteinFasta/data_out/H99_10p_up12dwn9_protein_with_nrAUG_Ntermext.fa")
```

## Process JEC21

```{r process_JEC21,results="show"}
expand_threeprime_nrstarts(txinfile = "../CDSFasta/data_in/JEC21_10p_up12dwn9_CDS_with_120bputrs.fa",
                        CDSoutfile="../CDSFasta/data_out/JEC21_10p_up12dwn9_CDS_with_nrAUG_5pext.fa",
                        protoutfile="../ProteinFasta/data_out/JEC21_10p_up12dwn9_protein_with_nrAUG_Ntermext.fa")
```

